name: Build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 21 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install fonttools brotli zopfli
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run build
      - run: npm run opt
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
