name: Lint

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.2.2
      - run: pip install fonttools
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npx patch-package
      - run: npm run lighthouse
